# Setup
name: Haskell School
url: https://haskellfoundation.github.io/
permalink: /blog/:title/
default_lang: en
exclude_from_localization: []
encoding: utf-8

plugins:
  - jekyll-assets
  # - jekyll-redirect-from
  - jekyll-sitemap
  - kramdown
  - uglifier
  - jekyll-archives

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'CONTRIBUTING.md', 'Gemfile', 'Gemfile.lock', 'GLOSSARY', 'Rakefile', 'README.md', 'vendor', 'LICENSE']
assets:
  compress:
    css: sass
    js:  uglifier
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts


ghc_version: 9.0

sitemap:
  file: '/sitemap.xml'
  include_posts:
    - '/index.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'

jekyll-archives:
  enabled: ['categories', 'tags', 'year']
  layout: archive
  permalinks:
    year: '/blog/years/:year/'
    category: '/blog/categories/:name/'
    tag: '/blog/tags/:name/'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Helpers
empty_array: []
